modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "abitmorehex"
version = "${version}"
displayName = "aBit More Hexcasting"
logoFile = "icon.png"
authors = "aBitOfSomething"
description = '''
Describe me!
'''

[[dependencies.abitmorehex]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.abitmorehex]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.abitmorehex]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.85,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.abitmorehex]]
modId = "hexcasting"
mandatory = true
versionRange = "[0.10.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.abitmorehex]]
modId="hexal"
mandatory=false
versionRange="*"
ordering="NONE"
side="BOTH"

